---
title: "Programa de Prevenci칩n & Control del Dengue | 2025"
format: 
  dashboard:
      nav-buttons: [twitter, github, facebook]
theme: custom.scss
---

```{r setup_21_puebla}
library(sf)
mapview::mapviewOptions(default = TRUE,
                        basemaps.color.shuffle = FALSE)
if(as.vector(Sys.info()["sysname"]) == "Darwin"){
load("/Users/fdzul/Documents/geocoding_mx/2025/8.RData/denmex_2025.RData")
} else if(as.vector(Sys.info()["sysname"]) == "Windows"){
   load("D:\\OneDrive\\proyects\\geocoding_mex\\2024\\8.RData\\denmex_2024.RData")
} else if(as.vector(Sys.info()["sysname"]) == "Linux"){
    load("/home/fdzul/Documents/active_transmission/geocoding_mx/8.RData/denmex_2025.RData")
}
library(magrittr)
```

# [**Cadenas de Transmisi칩n**]{style="font-size:8pt"}

::: panel-tabset


### [**Heroica Puebla de Zaragoza**]{style="color:#990000"}

```{r chain_puebla}
denhotspots::transmission_chains_map(geocoded_dataset = z,
                                     cve_edo = "21",
                                     locality = "Heroica Puebla de Zaragoza",
                                     dengue_cases = "Probable")
```



### [**Tehuac치n**]{style="color:#990000"}

```{r chain_tehuacan}
denhotspots::transmission_chains_map(geocoded_dataset = z,
                                     cve_edo = "21",
                                     locality = "Tehuacan",
                                     dengue_cases = "Probable")
```


### [**Izucar de Matamoros**]{style="color:#990000"}

```{r chain_izucar}
denhotspots::transmission_chains_map(geocoded_dataset = z,
                                     cve_edo = "21",
                                     locality = "Izucar de Matamoros",
                                     dengue_cases = "Probable")
```



:::


# [**Mapas de Calor**]{style="font-size:8pt"}

::: panel-tabset


### [**Heroica Puebla de Zaragoza**]{style="color:#990000"}
```{r heatmap_puebla}
densnv::mp_heatmap(geocoded_dataset = z,
                   cve_edo = "21",
                   locality = "Heroica Puebla de Zaragoza",
                   status_caso = c(1, 2),
                   kernel = 250,
                   week = c(1:53),
                   zoom = NULL,
                   map_type = NULL,
                   alpha = 0.6,
                   static = FALSE,
                    save = FALSE,
                   palette = viridis::turbo)
```

### [**Tehuac치n**]{style="color:#990000"}
```{r heatmap_tehuacan}
densnv::mp_heatmap(geocoded_dataset = z,
                   cve_edo = "21",
                   locality = "Tehuacan",
                   status_caso = c(1, 2),
                   week = c(1:53),
                   kernel = 380,
                   zoom = NULL,
                   map_type = NULL,
                   alpha = 0.6,
                   static = FALSE,
                    save = FALSE,
                   palette = viridis::turbo)
```

### [**Izucar de Matamoros**]{style="color:#990000"}
```{r heatmap_izucar}
densnv::mp_heatmap(geocoded_dataset = z,
                   cve_edo = "21",
                   locality = "Izucar de Matamoros",
                   status_caso = c(1, 2),
                   kernel = 1000,
                   week = c(1:53),
                   zoom = NULL,
                   map_type = NULL,
                   alpha = 0.6,
                   static = FALSE,
                    save = FALSE,
                   palette = viridis::turbo)
```



:::
